# Generated by Django 4.0.4 on 2022-04-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('artist', models.CharField(max_length=300)),
                ('album', models.CharField(max_length=300)),
                ('release_date', models.DateField()),
                ('genre', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
